sudo: required
services:
  - docker
before_install:
  # line of code for specifying the encrypted service json file (for gcloud auth)
  - curl https://sdk.cloud.google.com | bash > /dev/null; # download and install google cloud sdk on temporary vm in travis
  - source $HOME/google-cloud-sdk/path.bash.inc # some additional configuration on sdk
  - gcloud components update kubectl # download/update kubectl
  - gcloud auth activate-service-account --key-file service-account.json # (authroie gcloud using a service account whose credential will be present in the json file) similar to IAM user in AWS
  - gcloud config set project skilfulberm-4545 #(project ID)
  - gcloud config set compute/zone us-central-a
  - gcooud container clusters get-credentials multi-cluster # cluster name set in gcloud

